//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new after sales enquiry has been made. &lt;br&gt;
        ///&lt;br&gt;
        ///Distributor: {0}&lt;br&gt;
        ///Dealer: {1}&lt;br&gt;
        ///&lt;br&gt;
        ///Product: {2}&lt;br&gt;
        ///Site visit required: {3}&lt;br&gt;
        ///Comments: {4}&lt;br&gt;
        ///
        ///Please &lt;a href=&quot;{5}&quot;&gt;login&lt;/a&gt; for full details..
        /// </summary>
        public static string AfterSales_MailBody {
            get {
                return ResourceManager.GetString("AfterSales_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new comment has been posted for after sales enquiry {5} by {6}&lt;br&gt;
        ///Dealer: {0}&lt;br&gt;
        ///Product: {1}&lt;br&gt;
        ///Comment text:{2}&lt;br&gt;
        ///{3} files attached to comment.&lt;br&gt;
        ///
        ///Please &lt;a href=&quot;{4}&quot;&gt;login&lt;/a&gt; for full details..
        /// </summary>
        public static string AfterSales_NewComment_MailBody {
            get {
                return ResourceManager.GetString("AfterSales_NewComment_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New after sales enquiry comment has been made..
        /// </summary>
        public static string AfterSales_NewComment_MailSubject {
            get {
                return ResourceManager.GetString("AfterSales_NewComment_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site visit report has been submitted. &lt;br&gt;.
        /// </summary>
        public static string AfterSales_SiteVisit_SubmitCommentPrefix {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisit_SubmitCommentPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New site visit report was submitted.&lt;br&gt;
        ///Customer: {0}&lt;br&gt;
        ///Product: {1}&lt;br&gt;
        ///Comment by Crosswater: {2}&lt;br&gt;
        ///Please &lt;a href=&quot;{3}&quot;&gt;login&lt;/a&gt; to see details..
        /// </summary>
        public static string AfterSales_SiteVisitNotifyDistributor_MailBody {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisitNotifyDistributor_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New site visit report submitted.
        /// </summary>
        public static string AfterSales_SiteVisitNotifyDistributor_MailSubject {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisitNotifyDistributor_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been selected for site visit by {0}.&lt;br&gt;
        ///Product: {1}&lt;br&gt;
        ///Customer: {2}&lt;br&gt;
        ///Address:{3}&lt;br&gt;
        ///Message: {4}&lt;br&gt;
        ///Please &lt;a href=&quot;{5}&quot;&gt;login in&lt;/a&gt; for details
        ///.
        /// </summary>
        public static string AfterSales_SiteVisitRequest_MailBody {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisitRequest_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New site visit requested..
        /// </summary>
        public static string AfterSales_SiteVisitRequest_MailSubject {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisitRequest_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site visit report submitted by {0}&lt;br&gt;
        ///Product: {1}&lt;br&gt;
        ///Customer: {2}&lt;br&gt;
        ///Please &lt;a href=&quot;{3}&quot;&gt;login in&lt;/a&gt; for details
        ///.
        /// </summary>
        public static string AfterSales_SiteVisitSubmitted_MailBody {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisitSubmitted_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site visit report submitted..
        /// </summary>
        public static string AfterSales_SiteVisitSubmitted_MailSubject {
            get {
                return ResourceManager.GetString("AfterSales_SiteVisitSubmitted_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awaiting response.
        /// </summary>
        public static string AfterSales_Status_Awaiting {
            get {
                return ResourceManager.GetString("AfterSales_Status_Awaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awaiting distributor response.
        /// </summary>
        public static string AfterSales_Status_Awaiting_Master_Dist {
            get {
                return ResourceManager.GetString("AfterSales_Status_Awaiting_Master_Dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awaiting manufacturer response.
        /// </summary>
        public static string AfterSales_Status_Awaiting_Master_Manuf {
            get {
                return ResourceManager.GetString("AfterSales_Status_Awaiting_Master_Manuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string AfterSales_Status_New {
            get {
                return ResourceManager.GetString("AfterSales_Status_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processed.
        /// </summary>
        public static string AfterSales_Status_Processed {
            get {
                return ResourceManager.GetString("AfterSales_Status_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responded.
        /// </summary>
        public static string AfterSales_Status_Responded {
            get {
                return ResourceManager.GetString("AfterSales_Status_Responded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distributor responded.
        /// </summary>
        public static string AfterSales_Status_Responded_Dist {
            get {
                return ResourceManager.GetString("AfterSales_Status_Responded_Dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manufacturer responded.
        /// </summary>
        public static string AfterSales_Status_Responded_Manuf {
            get {
                return ResourceManager.GetString("AfterSales_Status_Responded_Manuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site visit requested.
        /// </summary>
        public static string AfterSales_Status_SiteVisitRequested {
            get {
                return ResourceManager.GetString("AfterSales_Status_SiteVisitRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awaiting report.
        /// </summary>
        public static string AfterSales_Status_SiteVisitRequestedDist {
            get {
                return ResourceManager.GetString("AfterSales_Status_SiteVisitRequestedDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site visit report submitted.
        /// </summary>
        public static string AfterSales_Status_SiteVisitSubmitted {
            get {
                return ResourceManager.GetString("AfterSales_Status_SiteVisitSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:A new after sales enquiry has been made.
        /// </summary>
        public static string AfterSales_Subject {
            get {
                return ResourceManager.GetString("AfterSales_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.
        /// </summary>
        public static string AfterSalesEnquiries_ChargeType_Customer {
            get {
                return ResourceManager.GetString("AfterSalesEnquiries_ChargeType_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dealer.
        /// </summary>
        public static string AfterSalesEnquiries_ChargeType_Dealer {
            get {
                return ResourceManager.GetString("AfterSalesEnquiries_ChargeType_Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distributor.
        /// </summary>
        public static string AfterSalesEnquiries_ChargeType_Distributor {
            get {
                return ResourceManager.GetString("AfterSalesEnquiries_ChargeType_Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrange for a site visit (3 business days).
        /// </summary>
        public static string AfterSalesEnquiries_ResponseType_SiteVisit {
            get {
                return ResourceManager.GetString("AfterSalesEnquiries_ResponseType_SiteVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an online technical response.
        /// </summary>
        public static string AfterSalesEnquiries_ResponseType_Tech {
            get {
                return ResourceManager.GetString("AfterSalesEnquiries_ResponseType_Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string AfterSalesEnquiriesComment_RespondTo_Manufacturer {
            get {
                return ResourceManager.GetString("AfterSalesEnquiriesComment_RespondTo_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site visit record with given id cannot be found.
        /// </summary>
        public static string AfterSalesSiteVisit_Wrongid {
            get {
                return ResourceManager.GetString("AfterSalesSiteVisit_Wrongid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automated message – please do not reply&lt;br&gt;
        ///Our recorded displays for UK Big Company have been updated.&lt;br&gt;
        ///You are now showing as the following dealer types:&lt;br&gt;
        ///{0}
        ///&lt;p&gt;
        ///.
        /// </summary>
        public static string ChangedDealer_DealerNotification_Body {
            get {
                return ResourceManager.GetString("ChangedDealer_DealerNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display records have been updated.
        /// </summary>
        public static string ChangedDealer_DealerNotification_Subject {
            get {
                return ResourceManager.GetString("ChangedDealer_DealerNotification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images for dealer {0} have been updated. Please amend their display products accordingly..
        /// </summary>
        public static string ChangedDealer_Dist_AdminNotification_Body {
            get {
                return ResourceManager.GetString("ChangedDealer_Dist_AdminNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dealer images updated.
        /// </summary>
        public static string ChangedDealer_Dist_AdminNotification_Subject {
            get {
                return ResourceManager.GetString("ChangedDealer_Dist_AdminNotification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select).
        /// </summary>
        public static string Combo_NotSelectedText {
            get {
                return ResourceManager.GetString("Combo_NotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.
        /// </summary>
        public static string Dealer_brochure_tablehead_customer {
            get {
                return ResourceManager.GetString("Dealer_brochure_tablehead_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date requested.
        /// </summary>
        public static string Dealer_brochure_tablehead_daterequest {
            get {
                return ResourceManager.GetString("Dealer_brochure_tablehead_daterequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date sent.
        /// </summary>
        public static string Dealer_brochure_tablehead_datesent {
            get {
                return ResourceManager.GetString("Dealer_brochure_tablehead_datesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Dealer_brochure_tablehead_email {
            get {
                return ResourceManager.GetString("Dealer_brochure_tablehead_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales status.
        /// </summary>
        public static string Dealer_brochure_tablehead_salestatus {
            get {
                return ResourceManager.GetString("Dealer_brochure_tablehead_salestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel.
        /// </summary>
        public static string Dealer_brochure_tablehead_tel {
            get {
                return ResourceManager.GetString("Dealer_brochure_tablehead_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display products for.
        /// </summary>
        public static string Dealer_displayprint_head {
            get {
                return ResourceManager.GetString("Dealer_displayprint_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print display items.
        /// </summary>
        public static string Dealer_displayprint_title {
            get {
                return ResourceManager.GetString("Dealer_displayprint_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Dealer_displayprod_confirmdist {
            get {
                return ResourceManager.GetString("Dealer_displayprod_confirmdist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our records show that your current distributor is.
        /// </summary>
        public static string Dealer_displayprod_distributorlabel {
            get {
                return ResourceManager.GetString("Dealer_displayprod_distributorlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm or adjust and confirm..
        /// </summary>
        public static string Dealer_displayprod_distributorlabel2 {
            get {
                return ResourceManager.GetString("Dealer_displayprod_distributorlabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print display items.
        /// </summary>
        public static string Dealer_displayprod_printbutton {
            get {
                return ResourceManager.GetString("Dealer_displayprod_printbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Requests.
        /// </summary>
        public static string Dealer_Image_Request_Header {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : tick the high resolution image and download the file.
        /// </summary>
        public static string Dealer_Image_Request_HighResInstructions {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_HighResInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Resolution Images.
        /// </summary>
        public static string Dealer_Image_Request_HighResLabel {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_HighResLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : click on the image to enlarge then right mouse click and select save picture as.
        /// </summary>
        public static string Dealer_Image_Request_LowResInstructions {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_LowResInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Resolution Images.
        /// </summary>
        public static string Dealer_Image_Request_LowResLabel {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_LowResLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string Dealer_Image_Request_TableHeader_code {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_TableHeader_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high res image.
        /// </summary>
        public static string Dealer_Image_Request_TableHeader_hires {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_TableHeader_hires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low res image.
        /// </summary>
        public static string Dealer_Image_Request_TableHeader_lowres {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_TableHeader_lowres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product name.
        /// </summary>
        public static string Dealer_Image_Request_TableHeader_prodname {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_TableHeader_prodname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product type.
        /// </summary>
        public static string Dealer_Image_Request_TableHeader_prodtype {
            get {
                return ResourceManager.GetString("Dealer_Image_Request_TableHeader_prodtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Dealer_index_address {
            get {
                return ResourceManager.GetString("Dealer_index_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Dealer_index_bus {
            get {
                return ResourceManager.GetString("Dealer_index_bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Dealer_index_company {
            get {
                return ResourceManager.GetString("Dealer_index_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact mobile.
        /// </summary>
        public static string Dealer_index_contactmobile {
            get {
                return ResourceManager.GetString("Dealer_index_contactmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string Dealer_index_contactname {
            get {
                return ResourceManager.GetString("Dealer_index_contactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions:.
        /// </summary>
        public static string Dealer_index_directions {
            get {
                return ResourceManager.GetString("Dealer_index_directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Dealer_index_distributor {
            get {
                return ResourceManager.GetString("Dealer_index_distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string Dealer_index_email {
            get {
                return ResourceManager.GetString("Dealer_index_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string Dealer_index_fax {
            get {
                return ResourceManager.GetString("Dealer_index_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Dealer_index_lat {
            get {
                return ResourceManager.GetString("Dealer_index_lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Dealer_index_long {
            get {
                return ResourceManager.GetString("Dealer_index_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Coordinates.
        /// </summary>
        public static string Dealer_index_mapcoord {
            get {
                return ResourceManager.GetString("Dealer_index_mapcoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening times.
        /// </summary>
        public static string Dealer_index_opening {
            get {
                return ResourceManager.GetString("Dealer_index_opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Dealer_index_password {
            get {
                return ResourceManager.GetString("Dealer_index_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Dealer_index_postcode {
            get {
                return ResourceManager.GetString("Dealer_index_postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail / Tube.
        /// </summary>
        public static string Dealer_index_rail {
            get {
                return ResourceManager.GetString("Dealer_index_rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road / Parking.
        /// </summary>
        public static string Dealer_index_road {
            get {
                return ResourceManager.GetString("Dealer_index_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORE NAME.
        /// </summary>
        public static string Dealer_index_storename {
            get {
                return ResourceManager.GetString("Dealer_index_storename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Dealer_index_submit {
            get {
                return ResourceManager.GetString("Dealer_index_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string Dealer_index_tel {
            get {
                return ResourceManager.GetString("Dealer_index_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Address &amp; Contact Details.
        /// </summary>
        public static string Dealer_index_vertical1 {
            get {
                return ResourceManager.GetString("Dealer_index_vertical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Opening Times.
        /// </summary>
        public static string Dealer_index_vertical2 {
            get {
                return ResourceManager.GetString("Dealer_index_vertical2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Dealer_index_website {
            get {
                return ResourceManager.GetString("Dealer_index_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dealer login.
        /// </summary>
        public static string Dealer_login_caption {
            get {
                return ResourceManager.GetString("Dealer_login_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distributor login.
        /// </summary>
        public static string Dealer_login_distributorcaption {
            get {
                return ResourceManager.GetString("Dealer_login_distributorcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong e-mail or password.
        /// </summary>
        public static string Dealer_login_failuretext {
            get {
                return ResourceManager.GetString("Dealer_login_failuretext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Dealer_login_forgotten_email {
            get {
                return ResourceManager.GetString("Dealer_login_forgotten_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter your email.
        /// </summary>
        public static string Dealer_login_forgotten_errormessage {
            get {
                return ResourceManager.GetString("Dealer_login_forgotten_errormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string Dealer_login_forgottenpass {
            get {
                return ResourceManager.GetString("Dealer_login_forgottenpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Dealer_login_logintype_dealer {
            get {
                return ResourceManager.GetString("Dealer_login_logintype_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Dealer_login_logintype_distributor {
            get {
                return ResourceManager.GetString("Dealer_login_logintype_distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Dealer_login_password {
            get {
                return ResourceManager.GetString("Dealer_login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Dealer_login_submit {
            get {
                return ResourceManager.GetString("Dealer_login_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Dealer_login_username {
            get {
                return ResourceManager.GetString("Dealer_login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required information is incomplete or contains errors:.
        /// </summary>
        public static string Dealer_login_validationsummary_text {
            get {
                return ResourceManager.GetString("Dealer_login_validationsummary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brochure requests.
        /// </summary>
        public static string Dealer_master_menu_br {
            get {
                return ResourceManager.GetString("Dealer_master_menu_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayed products.
        /// </summary>
        public static string Dealer_master_menu_displayed {
            get {
                return ResourceManager.GetString("Dealer_master_menu_displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image requests.
        /// </summary>
        public static string Dealer_master_menu_imgreq {
            get {
                return ResourceManager.GetString("Dealer_master_menu_imgreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Dealer_master_menu_logoff {
            get {
                return ResourceManager.GetString("Dealer_master_menu_logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store photos.
        /// </summary>
        public static string Dealer_master_menu_photos {
            get {
                return ResourceManager.GetString("Dealer_master_menu_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview store page.
        /// </summary>
        public static string Dealer_master_menu_preview {
            get {
                return ResourceManager.GetString("Dealer_master_menu_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product training.
        /// </summary>
        public static string Dealer_master_menu_training {
            get {
                return ResourceManager.GetString("Dealer_master_menu_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address/contact info, opening &lt;br /&gt;
        ///        times, directions.
        /// </summary>
        public static string Dealer_master_menulink_address {
            get {
                return ResourceManager.GetString("Dealer_master_menulink_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete this picture.
        /// </summary>
        public static string Dealer_photos_deletepicture {
            get {
                return ResourceManager.GetString("Dealer_photos_deletepicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store image pages (maximum {0} photos).
        /// </summary>
        public static string Dealer_photos_photonotice {
            get {
                return ResourceManager.GetString("Dealer_photos_photonotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name:.
        /// </summary>
        public static string Dealer_photos_storename {
            get {
                return ResourceManager.GetString("Dealer_photos_storename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        public static string Dealer_photos_uploadtext {
            get {
                return ResourceManager.GetString("Dealer_photos_uploadtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        ///&lt;p&gt;The Dealer has been confirmed and activated.&lt;/p&gt;.
        /// </summary>
        public static string DealerConfirm_text {
            get {
                return ResourceManager.GetString("DealerConfirm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Dealerdetails_address {
            get {
                return ResourceManager.GetString("Dealerdetails_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Bus.
        /// </summary>
        public static string Dealerdetails_bybus {
            get {
                return ResourceManager.GetString("Dealerdetails_bybus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Rail.
        /// </summary>
        public static string Dealerdetails_byrail {
            get {
                return ResourceManager.GetString("Dealerdetails_byrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Road.
        /// </summary>
        public static string Dealerdetails_byroad {
            get {
                return ResourceManager.GetString("Dealerdetails_byroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string Dealerdetails_directions {
            get {
                return ResourceManager.GetString("Dealerdetails_directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string Dealerdetails_email {
            get {
                return ResourceManager.GetString("Dealerdetails_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string Dealerdetails_fax {
            get {
                return ResourceManager.GetString("Dealerdetails_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map &amp; Address.
        /// </summary>
        public static string DealerDetails_Map {
            get {
                return ResourceManager.GetString("DealerDetails_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening times.
        /// </summary>
        public static string Dealerdetails_opentimes {
            get {
                return ResourceManager.GetString("Dealerdetails_opentimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products on display.
        /// </summary>
        public static string Dealerdetails_proddisplay {
            get {
                return ResourceManager.GetString("Dealerdetails_proddisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store information.
        /// </summary>
        public static string DealerDetails_StoreInfo {
            get {
                return ResourceManager.GetString("DealerDetails_StoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string Dealerdetails_tel {
            get {
                return ResourceManager.GetString("Dealerdetails_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds {0} M limit..
        /// </summary>
        public static string DealerImage_FileOverLimitMessage {
            get {
                return ResourceManager.GetString("DealerImage_FileOverLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your store location can be entered directly by updating the longitude and latitude fields or alternatively locate and click on the exact information in the map below and the coordinates will be updated automatically. Remember to click submit to save any changes..
        /// </summary>
        public static string DealerIndexPage_LatLongNote {
            get {
                return ResourceManager.GetString("DealerIndexPage_LatLongNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string DealerType_Gold {
            get {
                return ResourceManager.GetString("DealerType_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string DealerType_Silver {
            get {
                return ResourceManager.GetString("DealerType_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string DealerType_Standard {
            get {
                return ResourceManager.GetString("DealerType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FE Office.
        /// </summary>
        public static string Display_FEOffice {
            get {
                return ResourceManager.GetString("Display_FEOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry with given id cannot be found.
        /// </summary>
        public static string EnquiryWrongId {
            get {
                return ResourceManager.GetString("EnquiryWrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client: {0}&lt;br&gt;Factory: {1}&lt;br&gt;&lt;br&gt;Product: {2} - {3}&lt;br&gt;&lt;br&gt;What is the specific issue? {4} &lt;br&gt;&lt;br&gt;What is /are the specific question/s?  {5}  &lt;br&gt;&lt;br&gt;What is your suggestion for the resolution of this issue?  {6}&lt;br&gt;&lt;br&gt;Resolution:  {7}&lt;br&gt;&lt;br&gt;&lt;br&gt;Please check the system for full details&lt;br&gt;&lt;br&gt;&lt;br&gt;This is an automated message. Please do not reply to it.
        /// </summary>
        public static string Feedback_5_body {
            get {
                return ResourceManager.GetString("Feedback_5_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted by: {2}&lt;br&gt;What is the specific issue? {0} &lt;br&gt;&lt;br&gt;What is /are the specific question/s?  {1}  &lt;br&gt;Please check the system for &lt;a href=&quot;{3}/claims/itfeedback#/edit/{4}&quot;&gt;full details&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;This is an automated message. Please do not reply to it.
        /// </summary>
        public static string Feedback_6_body {
            get {
                return ResourceManager.GetString("Feedback_6_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;
        ///Reference: {0}&lt;br&gt;Category: {1}&lt;br&gt;
        ///Product: {2}
        ///&lt;br&gt;
        ///PO#: {3}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Date Submitted: {4}
        ///&lt;br&gt;
        ///Urgency: {5}
        ///&lt;br&gt;
        ///QC user names: {6}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Reason:	 {7}
        ///&lt;br&gt;
        ///Resolution-Prior to shipment the product: {8}
        ///&lt;br&gt;
        ///Permanent Action - How to prevent reoccurring: {9}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Rejection date: {10}
        ///&lt;br&gt;
        ///Recheck date: {11}
        ///&lt;br&gt;
        ///Recheck required: {12}
        ///&lt;br&gt;
        ///Recheck OK: {13}
        ///&lt;br&gt;
        ///Inspection qty: {14}
        ///&lt;br&gt;
        ///Sample qty: {15}
        ///&lt;br&gt;
        ///Rejection qty: {16}
        ///&lt;br&gt;
        ///&lt;br&gt;&lt;br&gt;Please check [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Feedback_7_body {
            get {
                return ResourceManager.GetString("Feedback_7_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: {0} &lt;br/&gt; Summary: {1} &lt;br/&gt; Description of the issue: {2} &lt;br&gt; Products: {3}. &lt;br&gt; Please check the system for &lt;a href=&quot;{4}/claims/qa#/edit/{5}&quot;&gt;full details&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;This is an automated message. Please do not reply to it.
        /// </summary>
        public static string Feedback_8_body {
            get {
                return ResourceManager.GetString("Feedback_8_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;
        ///Reference: {0}
        ///&lt;br&gt;
        ///Category: {1}
        ///&lt;br&gt;
        ///Product: {2}
        ///&lt;br&gt;
        ///PO#: {3}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Date Submitted: {4}
        ///&lt;br&gt;
        ///Urgency: {5}
        ///&lt;br&gt;
        ///QC user names: {6}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Reason:	 {7}
        ///&lt;br&gt;
        ///Resolution-Prior to shipment the product: {8}
        ///&lt;br&gt;
        ///Permanent Action - How to prevent reoccurring: {9}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Rejection date: {10}
        ///&lt;br&gt;
        ///Recheck date: {11}
        ///&lt;br&gt;
        ///Recheck required: {12}
        ///&lt;br&gt;
        ///Recheck OK: {13}
        ///&lt;br&gt;
        ///Inspection qty: {14}
        ///&lt;br&gt;
        ///Sample qty: {15}
        ///&lt;br&gt;
        ///Rejection qty: {16}
        ///&lt;br&gt;
        ///&lt;br&gt;.
        /// </summary>
        public static string Feedback_comment_5_body {
            get {
                return ResourceManager.GetString("Feedback_comment_5_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from: {0}&lt;br&gt;Response: {1}
        ///&lt;br&gt;&lt;br&gt;Please check the system for &lt;a href=&quot;{2}/claims/itfeedback#/edit/{3}&quot;&gt;full details&lt;/a&gt;
        ///&lt;br&gt;&lt;br&gt;&lt;br&gt;This is an automated message. Please do not reply to it.
        /// </summary>
        public static string Feedback_comment_6_body {
            get {
                return ResourceManager.GetString("Feedback_comment_6_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from: {0}&lt;br&gt;Response: {1}
        ///&lt;br&gt;&lt;br&gt;Please check the system for &lt;a href=&quot;{2}/claims/editca/{3}&quot;&gt;full details&lt;/a&gt;
        ///&lt;br&gt;&lt;br&gt;&lt;br&gt;This is an automated message. Please do not reply to it.
        /// </summary>
        public static string Feedback_comment_7_body {
            get {
                return ResourceManager.GetString("Feedback_comment_7_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from: {0}&lt;br&gt;Response: {1}
        ///&lt;br&gt;&lt;br&gt;Please check the system for &lt;a href=&quot;{2}/claims/qa#/edit/{3}&quot;&gt;full details&lt;/a&gt;
        ///&lt;br&gt;&lt;br&gt;&lt;br&gt;This is an automated message. Please do not reply to it.
        /// </summary>
        public static string Feedback_comment_8_body {
            get {
                return ResourceManager.GetString("Feedback_comment_8_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - client comment added.
        /// </summary>
        public static string Feedback_comment_subject {
            get {
                return ResourceManager.GetString("Feedback_comment_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;
        ///Reference: {0}&lt;br&gt;Submitted by: {18}&lt;br&gt;Category: {1}&lt;br&gt;
        ///Product: {2}
        ///&lt;br&gt;
        ///PO#: {3}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Date Submitted: {4}
        ///&lt;br&gt;
        ///Urgency: {5}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Reason:	 {6}
        ///&lt;br&gt;
        ///Resolution-Prior to shipment the product: {7}
        ///&lt;br&gt;
        ///Permanent Action - How to prevent reoccurring: {8}
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Rejection date: {9}
        ///&lt;br&gt;
        ///Recheck date: {10}
        ///&lt;br&gt;
        ///Recheck required: {11}
        ///&lt;br&gt;
        ///Recheck OK: {12}
        ///&lt;br&gt;
        ///Inspection qty: {13}
        ///&lt;br&gt;
        ///Sample qty: {14}
        ///&lt;br&gt;
        ///Rejection qty: {15}
        ///&lt;br&gt;
        ///&lt;br&gt;&lt;br&gt;Please check the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Feedback_recheck_body {
            get {
                return ResourceManager.GetString("Feedback_recheck_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-New {2} feedback submitted - {1}.
        /// </summary>
        public static string Feedback_subject {
            get {
                return ResourceManager.GetString("Feedback_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recheck Status {3} --  {0}- Product feedback rejection submitted - {1}.
        /// </summary>
        public static string Feedback_Subject_Rejection {
            get {
                return ResourceManager.GetString("Feedback_Subject_Rejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is larger than {0} MB..
        /// </summary>
        public static string FileTooBig {
            get {
                return ResourceManager.GetString("FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAQ.
        /// </summary>
        public static string Inspection_Admin_Id {
            get {
                return ResourceManager.GetString("Inspection_Admin_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East China.
        /// </summary>
        public static string Inspection_Location1_Title {
            get {
                return ResourceManager.GetString("Inspection_Location1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South China.
        /// </summary>
        public static string Inspection_Location2_Title {
            get {
                return ResourceManager.GetString("Inspection_Location2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North China.
        /// </summary>
        public static string Inspection_Location3_Title {
            get {
                return ResourceManager.GetString("Inspection_Location3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location4.
        /// </summary>
        public static string Inspection_Location4_Title {
            get {
                return ResourceManager.GetString("Inspection_Location4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT ticket &quot;{0}&quot; has been updated by {1}.&lt;br&gt;
        ///comments: {2}&lt;br&gt;
        ///
        ///.
        /// </summary>
        public static string Issues_CommentAdded_MailBody {
            get {
                return ResourceManager.GetString("Issues_CommentAdded_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT ticket &quot;{0}&quot; ticket has been updated.
        /// </summary>
        public static string Issues_CommentAdded_Subject {
            get {
                return ResourceManager.GetString("Issues_CommentAdded_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue with given id cannot be found..
        /// </summary>
        public static string IssueWrongId {
            get {
                return ResourceManager.GetString("IssueWrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string Login_Validation_invaliduserandpassword {
            get {
                return ResourceManager.GetString("Login_Validation_invaliduserandpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new dealer has been created:&lt;br&gt;
        ///
        ///Distributor: {0}&lt;br&gt;
        ///
        ///Dealer name: {1}&lt;br&gt;
        ///&lt;br&gt;
        ///
        ///Please log in to update the displays and confirm the dealer..
        /// </summary>
        public static string NewDealer_AdminNotification_Body {
            get {
                return ResourceManager.GetString("NewDealer_AdminNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations you have been confirmed as a {0} {1} dealer.&lt;br&gt;
        ///
        ///Please click &lt;a href=&quot;{2}&quot;&gt;here&lt;/a&gt; to activate your account..&lt;br&gt;
        ///{3}&lt;p&gt;
        ///This is an automated message – please do not reply.
        /// </summary>
        public static string NewDealer_Live_Body {
            get {
                return ResourceManager.GetString("NewDealer_Live_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the images you have uploaded we have identified and added the following products as displays:
        ///{0}.
        /// </summary>
        public static string NewDealer_Live_ImagesText_HasImages {
            get {
                return ResourceManager.GetString("NewDealer_Live_ImagesText_HasImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images have been uploaded.
        /// </summary>
        public static string NewDealer_Live_ImagesText_NoImages {
            get {
                return ResourceManager.GetString("NewDealer_Live_ImagesText_NoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Dealer.
        /// </summary>
        public static string NewDealer_Live_Subject {
            get {
                return ResourceManager.GetString("NewDealer_Live_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new UK Big Company  dealer has been created.
        /// </summary>
        public static string NewDealer_Subject {
            get {
                return ResourceManager.GetString("NewDealer_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare / Samples Loading Notification.
        /// </summary>
        public static string NsReportTitle {
            get {
                return ResourceManager.GetString("NsReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved / Changed Product Loading Notification.
        /// </summary>
        public static string NtReportTitle {
            get {
                return ResourceManager.GetString("NtReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete this picture.
        /// </summary>
        public static string Photos_deletepicture {
            get {
                return ResourceManager.GetString("Photos_deletepicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with given id cannot be found.
        /// </summary>
        public static string RecordWrongId {
            get {
                return ResourceManager.GetString("RecordWrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ReturnsStatus_Closed {
            get {
                return ResourceManager.GetString("ReturnsStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ReturnsStatus_New {
            get {
                return ResourceManager.GetString("ReturnsStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string ReturnsStatus_Progress {
            get {
                return ResourceManager.GetString("ReturnsStatus_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local dealers.
        /// </summary>
        public static string SalesRepCompareValue_LocalDealers {
            get {
                return ResourceManager.GetString("SalesRepCompareValue_LocalDealers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local displaying dealers.
        /// </summary>
        public static string SalesRepCompareValue_LocalDisplaying {
            get {
                return ResourceManager.GetString("SalesRepCompareValue_LocalDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local non-displaying dealers.
        /// </summary>
        public static string SalesRepCompareValue_LocalNondisplaying {
            get {
                return ResourceManager.GetString("SalesRepCompareValue_LocalNondisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous period.
        /// </summary>
        public static string SalesRepCompareValue_Previous {
            get {
                return ResourceManager.GetString("SalesRepCompareValue_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SalesRepProduct_All {
            get {
                return ResourceManager.GetString("SalesRepProduct_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom 10.
        /// </summary>
        public static string SalesRepProduct_BottomN {
            get {
                return ResourceManager.GetString("SalesRepProduct_BottomN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayed products only.
        /// </summary>
        public static string SalesRepProduct_Displayed {
            get {
                return ResourceManager.GetString("SalesRepProduct_Displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 10.
        /// </summary>
        public static string SalesRepProduct_TopN {
            get {
                return ResourceManager.GetString("SalesRepProduct_TopN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simple-input.
        /// </summary>
        public static string SimpleInput {
            get {
                return ResourceManager.GetString("SimpleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £ 150.
        /// </summary>
        public static string SiteVisitPrice {
            get {
                return ResourceManager.GetString("SiteVisitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string Uploader_uploadfailedmessage {
            get {
                return ResourceManager.GetString("Uploader_uploadfailedmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be deleted because it or its children are related to one or more issues. First few entries are: &lt;br&gt;{0}.
        /// </summary>
        public static string Validation_CategoryCannotBeDeleted {
            get {
                return ResourceManager.GetString("Validation_CategoryCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be specified..
        /// </summary>
        public static string Validation_PasswordRequired {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired", resourceCulture);
            }
        }
    }
}
