//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comment_Files")]
        public string CommentFiles_SessionVar {
            get {
                return ((string)(this["CommentFiles_SessionVar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public decimal SiteVisit_Price {
            get {
                return ((decimal)(this["SiteVisit_Price"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Files/")]
        public string Enquiries_FilesFolder {
            get {
                return ((string)(this["Enquiries_FilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float Enquiries_MaxFileSize {
            get {
                return ((float)(this["Enquiries_MaxFileSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMTPPassword {
            get {
                return ((string)(this["SMTPPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/SiteVisitsFiles/")]
        public string SiteVisits_FilesFolder {
            get {
                return ((string)(this["SiteVisits_FilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AfterSalesCC {
            get {
                return ((string)(this["AfterSalesCC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AfterSalesBcc {
            get {
                return ((string)(this["AfterSalesBcc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyCleE5vbeb8HtYMso0gj5btzA2iD4li2nA")]
        public string GoogleMap_Key {
            get {
                return ((string)(this["GoogleMap_Key"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/_user_application/store_management.asp")]
        public string dealermanagement_url {
            get {
                return ((string)(this["dealermanagement_url"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DealerStore_MaximumPhotos {
            get {
                return ((int)(this["DealerStore_MaximumPhotos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/dealers/")]
        public string dealerImagesFolder {
            get {
                return ((string)(this["dealerImagesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>closed</string>
  <string>07:00</string>
  <string>07:30</string>
  <string>08:00</string>
  <string>08:30</string>
  <string>09:00</string>
  <string>09:30</string>
  <string>10:00</string>
  <string>10:30</string>
  <string>11:00</string>
  <string>11:30</string>
  <string>12:00</string>
  <string>12:30</string>
  <string>13:00</string>
  <string>13:30</string>
  <string>14:00</string>
  <string>14:30</string>
  <string>15:00</string>
  <string>15:30</string>
  <string>16:00</string>
  <string>16:30</string>
  <string>17:00</string>
  <string>17:30</string>
  <string>18:00</string>
  <string>18:30</string>
  <string>19:00</string>
  <string>20:00</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StoreOpeningTimeValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StoreOpeningTimeValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>closed</string>
  <string>08:00</string>
  <string>09:00</string>
  <string>10:00</string>
  <string>11:00</string>
  <string>12:00</string>
  <string>13:00</string>
  <string>14:00</string>
  <string>15:00</string>
  <string>16:00</string>
  <string>17:00</string>
  <string>17:30</string>
  <string>18:00</string>
  <string>18:30</string>
  <string>19:00</string>
  <string>20:00</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StoreClosingTimeValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StoreClosingTimeValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewDealer_Cc {
            get {
                return ((string)(this["NewDealer_Cc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double VAT {
            get {
                return ((double)(this["VAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/")]
        public string imagesRootFolder {
            get {
                return ((string)(this["imagesRootFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("208,247")]
        public string distributors_with_old_design {
            get {
                return ((string)(this["distributors_with_old_design"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/feedback")]
        public string returns_fileroot {
            get {
                return ((string)(this["returns_fileroot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/manual/")]
        public string ManualImagesRoot {
            get {
                return ((string)(this["ManualImagesRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/manual/upload/")]
        public string ManualImagesUpload {
            get {
                return ((string)(this["ManualImagesUpload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableNewDesignForHeadDistributor {
            get {
                return ((bool)(this["EnableNewDesignForHeadDistributor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("282")]
        public string Inspectors_Exclusions {
            get {
                return ((string)(this["Inspectors_Exclusions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asaqback")]
        public string EventLogSource {
            get {
                return ((string)(this["EventLogSource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public string TranslationEditors {
            get {
                return ((string)(this["TranslationEditors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{00BAA5E3-2E27-41A8-9032-6E745453489D}")]
        public string StatsKey {
            get {
                return ((string)(this["StatsKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("282")]
        public string Inspectors_SeeUnallocated {
            get {
                return ((string)(this["Inspectors_SeeUnallocated"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8,11,14,17")]
        public string Analytics_OtherCategories_ids {
            get {
                return ((string)(this["Analytics_OtherCategories_ids"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/analytics")]
        public string Analytics_ImagesFolder {
            get {
                return ((string)(this["Analytics_ImagesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("273")]
        public string Analytics_ExcludedDistributors {
            get {
                return ((string)(this["Analytics_ExcludedDistributors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("appimages")]
        public string mobileAppImagesSubfolder {
            get {
                return ((string)(this["mobileAppImagesSubfolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8A4wrZepm64D7sw8b55m6969jZ89WZ")]
        public string AdminKey {
            get {
                return ((string)(this["AdminKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/npdFiles")]
        public string npdFilesFolders {
            get {
                return ((string)(this["npdFilesFolders"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double StockOrderCalculationThreshold {
            get {
                return ((double)(this["StockOrderCalculationThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ukbbl.gif")]
        public string AnalyticsLogoUK {
            get {
                return ((string)(this["AnalyticsLogoUK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Analytics_BrandSales_NumOfProductsPerBrand {
            get {
                return ((int)(this["Analytics_BrandSales_NumOfProductsPerBrand"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("907")]
        public int Analyitics_BrandSales_CleargreenTrays {
            get {
                return ((int)(this["Analyitics_BrandSales_CleargreenTrays"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{2D632DB6-1996-4B27-84E4-C0614831A1A1}")]
        public string StatsKey2 {
            get {
                return ((string)(this["StatsKey2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201")]
        public int Analyitics_BrandSales_ClearwaterBaths {
            get {
                return ((int)(this["Analyitics_BrandSales_ClearwaterBaths"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7,8,9,10,3,5")]
        public string Dealer_BrandsNoEmail {
            get {
                return ((string)(this["Dealer_BrandsNoEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nondistributors_with_new_design {
            get {
                return ((string)(this["nondistributors_with_new_design"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,282")]
        public string Feedback_subscribers_5 {
            get {
                return ((string)(this["Feedback_subscribers_5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int Feedback_pg_chart_width {
            get {
                return ((int)(this["Feedback_pg_chart_width"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Feedback_pg_chart_height {
            get {
                return ((int)(this["Feedback_pg_chart_height"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Feedback_subscribers_6 {
            get {
                return ((string)(this["Feedback_subscribers_6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int StockSummaryChart_width {
            get {
                return ((int)(this["StockSummaryChart_width"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int StockSummaryChart_height {
            get {
                return ((int)(this["StockSummaryChart_height"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Files")]
        public string Reports_FilesFolder {
            get {
                return ((string)(this["Reports_FilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750")]
        public int SurveyChart_Bar_Width {
            get {
                return ((int)(this["SurveyChart_Bar_Width"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SurveyChart_Bar_Height {
            get {
                return ((int)(this["SurveyChart_Bar_Height"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SurveyChart_Pie_Width {
            get {
                return ((int)(this["SurveyChart_Pie_Width"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SurveyChart_Pie_Height {
            get {
                return ((int)(this["SurveyChart_Pie_Height"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string StockSummary_FactoriesIgnoreStock {
            get {
                return ((string)(this["StockSummary_FactoriesIgnoreStock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45,55,149,321,1105")]
        public string OMExport_9RefClients {
            get {
                return ((string)(this["OMExport_9RefClients"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/salesrep/graphs/")]
        public string SalesRepGraphsFolder {
            get {
                return ((string)(this["SalesRepGraphsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570")]
        public int SalesRepGraphWidth {
            get {
                return ((int)(this["SalesRepGraphWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public int SalesRepGraphHeight {
            get {
                return ((int)(this["SalesRepGraphHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double CWImportSalesLowerLimit {
            get {
                return ((double)(this["CWImportSalesLowerLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37")]
        public string PrintCreditNote_ClientsWithBSLogo {
            get {
                return ((string)(this["PrintCreditNote_ClientsWithBSLogo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public string BrandDocuments_IncludedClients {
            get {
                return ((string)(this["BrandDocuments_IncludedClients"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<1500,1500-3000,3000-5000,>5000")]
        public string SalesRep_SqFeetValues {
            get {
                return ((string)(this["SalesRep_SqFeetValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<500k,500k-1m,1m-2m,>2m")]
        public string SalesRep_TurnoverValues {
            get {
                return ((string)(this["SalesRep_TurnoverValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200,37")]
        public string BulkDownLoadMultipleUsers {
            get {
                return ((string)(this["BulkDownLoadMultipleUsers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5,10,25,50,75")]
        public string SalesRep_Radiuses {
            get {
                return ((string)(this["SalesRep_Radiuses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int SalesRepGraphWidth2 {
            get {
                return ((int)(this["SalesRepGraphWidth2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45,55,149,53")]
        public string StockAllocationClients {
            get {
                return ((string)(this["StockAllocationClients"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/clients/returns/")]
        public string ReturnsImagesFolder {
            get {
                return ((string)(this["ReturnsImagesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/no_image.jpg")]
        public string No_image {
            get {
                return ((string)(this["No_image"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public string Issue_MaxFile {
            get {
                return ((string)(this["Issue_MaxFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float SiteVisits_MaxFileSize {
            get {
                return ((float)(this["SiteVisits_MaxFileSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string Image_BrandId {
            get {
                return ((string)(this["Image_BrandId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,282")]
        public string Feedback_subscribers {
            get {
                return ((string)(this["Feedback_subscribers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}-New product feedback submitted - {1}")]
        public string Feedback_Subject {
            get {
                return ((string)(this["Feedback_Subject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Client: {0}<br>Factory: {1}<br><br>Product: {2} - {3}<br><br>What is the specific issue? {4} <br><br>What is /are the specific question/s?  {5}  <br><br>What is your suggestion for the resolution of this issue?  {6}<br><br>Resolution:  {7}<br><br><br>Please check the system for full details<br><br><br>This is an automated message. Please do not reply to it")]
        public string Product_feedback_body {
            get {
                return ((string)(this["Product_feedback_body"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DownloadGroupType {
            get {
                return ((int)(this["DownloadGroupType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SalesRep_TopProducts {
            get {
                return ((int)(this["SalesRep_TopProducts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SalesRep_PieSliceThreshold {
            get {
                return ((int)(this["SalesRep_PieSliceThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Images/updates/")]
        public string ClaimsReportImage {
            get {
                return ((string)(this["ClaimsReportImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Analytics_PreviousYearSeriesColor {
            get {
                return ((global::System.Drawing.Color)(this["Analytics_PreviousYearSeriesColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSkyBlue")]
        public global::System.Drawing.Color Analytics_CurrentYearSeriesColor {
            get {
                return ((global::System.Drawing.Color)(this["Analytics_CurrentYearSeriesColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102, 255, 102")]
        public global::System.Drawing.Color Analytics_PreviousYearBudgetColor {
            get {
                return ((global::System.Drawing.Color)(this["Analytics_PreviousYearBudgetColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 153, 51")]
        public global::System.Drawing.Color Analytics_CurrentYearBudgetColor {
            get {
                return ((global::System.Drawing.Color)(this["Analytics_CurrentYearBudgetColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 51, 0")]
        public global::System.Drawing.Color Analytics_NextYearSeriesColor {
            get {
                return ((global::System.Drawing.Color)(this["Analytics_NextYearSeriesColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int Analytics_NextYearThreshold {
            get {
                return ((int)(this["Analytics_NextYearThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,4,11")]
        public string DealerStatus_Brands {
            get {
                return ((string)(this["DealerStatus_Brands"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Analytics_BrochureRequest_Months {
            get {
                return ((int)(this["Analytics_BrochureRequest_Months"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,4,11")]
        public string Analytics_Brochure_WebSites {
            get {
                return ((string)(this["Analytics_Brochure_WebSites"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Appearance,Dimension,Function,Material,Packaging")]
        public string InspectionCategories {
            get {
                return ((string)(this["InspectionCategories"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\projects\\data\\logs")]
        public string LogFilesPath {
            get {
                return ((string)(this["LogFilesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AuaCtghDJwoJLxkoE1NvUwLcdmAvOOvVR-sp12ci_D6gML68Ifb_siUO9tXJND-C")]
        public string BingMapKey {
            get {
                return ((string)(this["BingMapKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Images/report/monthly_brochure_requests")]
        public string Report_BrochureRequests_ImagesFolder {
            get {
                return ((string)(this["Report_BrochureRequests_ImagesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,4,11")]
        public string DealerExport_Brands {
            get {
                return ((string)(this["DealerExport_Brands"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79,85,211,103,95,97")]
        public string DealerExport_Distributors {
            get {
                return ((string)(this["DealerExport_Distributors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/cprod/image/")]
        public string CustProductImagesRoot {
            get {
                return ((string)(this["CustProductImagesRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload")]
        public string MastProductImagesRoot {
            get {
                return ((string)(this["MastProductImagesRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/tech/")]
        public string MastProductInstructionsRoot {
            get {
                return ((string)(this["MastProductInstructionsRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/cprod/dwg/")]
        public string CustProductDrawingsRoot {
            get {
                return ((string)(this["CustProductDrawingsRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/cprod/dwg_891")]
        public string CustProductDrawingsPngRoot {
            get {
                return ((string)(this["CustProductDrawingsPngRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/tech/dwg")]
        public string MastProductDrawingsRoot {
            get {
                return ((string)(this["MastProductDrawingsRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/tech/dwg_891")]
        public string MastProductDrawingsPngRoot {
            get {
                return ((string)(this["MastProductDrawingsPngRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/cprod/instructions/")]
        public string CustProductInstructionsRoot {
            get {
                return ((string)(this["CustProductInstructionsRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AR")]
        public string BrandCode {
            get {
                return ((string)(this["BrandCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("464")]
        public int FirstDealerId {
            get {
                return ((int)(this["FirstDealerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string NewDealerEditUserIds {
            get {
                return ((string)(this["NewDealerEditUserIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MDIwNjg2MmJjZmI0NDNlY2I2MWRhZTA3MzlhMDVkNmM=")]
        public string ApplicationKey {
            get {
                return ((string)(this["ApplicationKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PyE/Pz8/Ckc/Pz9cP2E/b3s9Pz9SLjI/AD8/IT8VbD8=")]
        public string ApplicationSecret {
            get {
                return ((string)(this["ApplicationSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29000")]
        public int Delay_grabzit {
            get {
                return ((int)(this["Delay_grabzit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/report/brand_baners/")]
        public string BrandImages_folder {
            get {
                return ((string)(this["BrandImages_folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InspectionDownload_exludedDocType {
            get {
                return ((int)(this["InspectionDownload_exludedDocType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/changenotices")]
        public string ChangeNoticeRootFolder {
            get {
                return ((string)(this["ChangeNoticeRootFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/templates/")]
        public string TemplatesFolder {
            get {
                return ((string)(this["TemplatesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MeetingFiles/")]
        public string MeetingFilesFolder {
            get {
                return ((string)(this["MeetingFilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int NewDealerDefaultSiteId {
            get {
                return ((int)(this["NewDealerDefaultSiteId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/qc/")]
        public string InspectionImagesFolder {
            get {
                return ((string)(this["InspectionImagesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G7 2TH,G12")]
        public string Product_HideInReports {
            get {
                return ((string)(this["Product_HideInReports"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomersForOrderingPatterns {
            get {
                return ((string)(this["CustomersForOrderingPatterns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/instructions")]
        public string InstructionExternaFolder {
            get {
                return ((string)(this["InstructionExternaFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qc_archive/pre2013")]
        public string InspectionImagesPre2013Folder {
            get {
                return ((string)(this["InspectionImagesPre2013Folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://server1:8082")]
        public string aspsite_root {
            get {
                return ((string)(this["aspsite_root"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("333")]
        public string EBInvoiceClientExceptions {
            get {
                return ((string)(this["EBInvoiceClientExceptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("333")]
        public string InspectionReport_ClientsForSupplierCodeReplacement {
            get {
                return ((string)(this["InspectionReport_ClientsForSupplierCodeReplacement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,6,11")]
        public string BrandsWithAnalyticsOption {
            get {
                return ((string)(this["BrandsWithAnalyticsOption"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClaimsReportImagesTempFolder {
            get {
                return ((string)(this["ClaimsReportImagesTempFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ITFeedback_ListLimit {
            get {
                return ((int)(this["ITFeedback_ListLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Feedback_subscribers_7 {
            get {
                return ((string)(this["Feedback_subscribers_7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qc_archive/2013")]
        public string InspectionImages2013Folder {
            get {
                return ((string)(this["InspectionImages2013Folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200,292,37,333")]
        public string NonBrandInvoices_IgnoredClients {
            get {
                return ((string)(this["NonBrandInvoices_IgnoredClients"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BulkDownload_CombineFactories {
            get {
                return ((bool)(this["BulkDownload_CombineFactories"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public string OMExport_ExcludedDistributors {
            get {
                return ((string)(this["OMExport_ExcludedDistributors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79,85,211,103,95,97,238")]
        public string DealerExport_InternationalDistributors {
            get {
                return ((string)(this["DealerExport_InternationalDistributors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tech/dwg/large_converted/")]
        public string imagesFolder_HiRes {
            get {
                return ((string)(this["imagesFolder_HiRes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Disabled_ForTestingOnStaging {
            get {
                return ((bool)(this["Disabled_ForTestingOnStaging"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ApplicationId {
            get {
                return ((int)(this["ApplicationId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qc_archive/2014")]
        public string InspectionImages2014Folder {
            get {
                return ((string)(this["InspectionImages2014Folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10 years domestic installations")]
        public string Guarantee_10y {
            get {
                return ((string)(this["Guarantee_10y"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 year commercial installations")]
        public string Guarantee_1y {
            get {
                return ((string)(this["Guarantee_1y"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Files")]
        public string TrackingNumberFilesFolder {
            get {
                return ((string)(this["TrackingNumberFilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=\"Excel 12.0" +
            " Xml;HDR=YES;IMEX=1\";")]
        public string connExcelNew {
            get {
                return ((string)(this["connExcelNew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source={0};Extended Properties=\"Excel 8.0\"")]
        public string connExcel {
            get {
                return ((string)(this["connExcel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DealerConfirmed_CC {
            get {
                return ((string)(this["DealerConfirmed_CC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/onlinetraining/")]
        public string OnlineTrainingFiles {
            get {
                return ((string)(this["OnlineTrainingFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-13")]
        public int HoursAdd_forUsaTime {
            get {
                return ((int)(this["HoursAdd_forUsaTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/USfeedback")]
        public string returns_USfileroot {
            get {
                return ((string)(this["returns_USfileroot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GB,UK,IE,US,CA")]
        public string DealerSequenceExcludedCountries {
            get {
                return ((string)(this["DealerSequenceExcludedCountries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string FeedbackSubscribers_M_CA {
            get {
                return ((string)(this["FeedbackSubscribers_M_CA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/nr")]
        public string NrImagesRootUrl {
            get {
                return ((string)(this["NrImagesRootUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}- Product feedback rejection submitted - {1}")]
        public string Feedback_Subject_Rejection {
            get {
                return ((string)(this["Feedback_Subject_Rejection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SMTPServerPortNumber {
            get {
                return ((int)(this["SMTPServerPortNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SMTPSslEnable {
            get {
                return ((bool)(this["SMTPSslEnable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TestMails {
            get {
                return ((string)(this["TestMails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none@none.com")]
        public string NoneEmail {
            get {
                return ((string)(this["NoneEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int Ammara_BrandId {
            get {
                return ((int)(this["Ammara_BrandId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyCu3508i9tm_HHGSLlzoXiLqgp-9B-5YKc ")]
        public string apimap_key {
            get {
                return ((string)(this["apimap_key"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sageApiKey {
            get {
                return ((string)(this["sageApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:60375")]
        public string sageApiUrl {
            get {
                return ((string)(this["sageApiUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string slaveHostApiKey {
            get {
                return ((string)(this["slaveHostApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images/upload/us_call_log")]
        public string UsCallLog_fileroot {
            get {
                return ((string)(this["UsCallLog_fileroot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("283;79")]
        public string CreditNotes_CompanyMappings {
            get {
                return ((string)(this["CreditNotes_CompanyMappings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.bigcompany.com")]
        public string SMTPServer {
            get {
                return ((string)(this["SMTPServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("enquiries@bigcompany.com")]
        public string SMTPAccount {
            get {
                return ((string)(this["SMTPAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bigcompany.com/dealer/imagepolicy?id={0}")]
        public string DealerImagePolicyLink {
            get {
                return ((string)(this["DealerImagePolicyLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logo.jpg")]
        public string AnalyticsLogoNonUK {
            get {
                return ((string)(this["AnalyticsLogoNonUK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("technical@bigcompany.com")]
        public string Feedback_To {
            get {
                return ((string)(this["Feedback_To"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reports@bigcompany.com")]
        public string Feedback_From {
            get {
                return ((string)(this["Feedback_From"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ben@bigcompany.com")]
        public string OrderQuantityAnalysis_to {
            get {
                return ((string)(this["OrderQuantityAnalysis_to"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("showroom@bigcompany.com")]
        public string EnquiriesFromAccount {
            get {
                return ((string)(this["EnquiriesFromAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@bigcompany.com")]
        public string FromAccount {
            get {
                return ((string)(this["FromAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bigcompany.com/clients/logos/")]
        public string LogosFolder {
            get {
                return ((string)(this["LogosFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("david@bigcompany.com")]
        public string DebugMailReceiver {
            get {
                return ((string)(this["DebugMailReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@bigcompany.com")]
        public string AutoUpdatersAppInfoMail {
            get {
                return ((string)(this["AutoUpdatersAppInfoMail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tvrtko@bigcompany.com")]
        public string Feedback_Bcc {
            get {
                return ((string)(this["Feedback_Bcc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ben@bigcompany.com")]
        public string NewDealer_Bcc {
            get {
                return ((string)(this["NewDealer_Bcc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ben@bigcompany.com")]
        public string NewDealer_Bcc1 {
            get {
                return ((string)(this["NewDealer_Bcc1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("david@bigcompany.com")]
        public string Feedback_Cc {
            get {
                return ((string)(this["Feedback_Cc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("monica@bigcompany.com")]
        public string NewDealer_EmailRecipients {
            get {
                return ((string)(this["NewDealer_EmailRecipients"]));
            }
        }
    }
}
