//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("erp.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification must be chosen..
        /// </summary>
        internal static string After_sales_enquiry_Validation_classification {
            get {
                return ResourceManager.GetString("After_sales_enquiry_Validation_classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product should be specified.
        /// </summary>
        internal static string After_sales_enquiry_Validation_cprod {
            get {
                return ResourceManager.GetString("After_sales_enquiry_Validation_cprod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name must be specified.
        /// </summary>
        internal static string After_sales_enquiry_Validation_customername {
            get {
                return ResourceManager.GetString("After_sales_enquiry_Validation_customername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number must be set.
        /// </summary>
        internal static string After_sales_enquiry_Validation_reference {
            get {
                return ResourceManager.GetString("After_sales_enquiry_Validation_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name should be specified.
        /// </summary>
        internal static string cust_products_Validation_name {
            get {
                return ResourceManager.GetString("cust_products_Validation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail must be supplied.
        /// </summary>
        internal static string Dealer_Validation_email {
            get {
                return ResourceManager.GetString("Dealer_Validation_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer name must be supplied.
        /// </summary>
        internal static string Dealer_Validation_name {
            get {
                return ResourceManager.GetString("Dealer_Validation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter the firstname.
        /// </summary>
        internal static string ExternalUser_Validation_firstname {
            get {
                return ResourceManager.GetString("ExternalUser_Validation_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter user&apos;s surname.
        /// </summary>
        internal static string ExternalUser_Validation_surname {
            get {
                return ResourceManager.GetString("ExternalUser_Validation_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter user&apos;s username.
        /// </summary>
        internal static string ExternalUser_Validation_username {
            get {
                return ResourceManager.GetString("ExternalUser_Validation_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be specified..
        /// </summary>
        internal static string IssueValidation_Title {
            get {
                return ResourceManager.GetString("IssueValidation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area must be specified..
        /// </summary>
        internal static string IssueValidaton_Area {
            get {
                return ResourceManager.GetString("IssueValidaton_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter your surname.
        /// </summary>
        internal static string validation_brochure_surname {
            get {
                return ResourceManager.GetString("validation_brochure_surname", resourceCulture);
            }
        }
    }
}
