//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asaq2.WebSites.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asaq2.WebSites.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for requesting our {0} brochure. &lt;br&gt;
        ///
        ///Your brochure will be sent to the following address:&lt;br&gt;&lt;br&gt;
        ///
        ///{1}
        ///
        ///&lt;br&gt;&lt;br&gt;This will be sent shortly and you should receive your brochure within 7 working days.
        /// </summary>
        internal static string MailToClientBody {
            get {
                return ResourceManager.GetString("MailToClientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of {0} brochure request (ref #{1}).
        /// </summary>
        internal static string MailToClientSubject {
            get {
                return ResourceManager.GetString("MailToClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please arrange for a {0} brochure to be sent to the following customer:&lt;br&gt;&lt;br&gt;
        ///{1}&lt;br&gt;
        ///{2}
        ///&lt;br&gt;&lt;br&gt;Many thanks.
        ///Bathroombrands automated messaging system.
        /// </summary>
        internal static string MailToDistributorBody {
            get {
                return ResourceManager.GetString("MailToDistributorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} brochure request (ref #{1}).
        /// </summary>
        internal static string MailToDistributorSubject {
            get {
                return ResourceManager.GetString("MailToDistributorSubject", resourceCulture);
            }
        }
    }
}
